# Generated by Django 2.1.7 on 2019-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('designation', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('price', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('region_1', models.CharField(max_length=100)),
                ('region_2', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=150)),
                ('winery', models.CharField(max_length=150)),
            ],
        ),
    ]
